version: "2"
services:
  api:
    build: .
    restart: always
    environment:
      - DB_ADDRESS=db
      - DB_USER=skillbridge
      - DB_PASSWORD=skillbridge
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=skillbridge
      - POSTGRES_PASSWORD=skillbridge
      - POSTGRES_DB=skillbridge
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"


volumes:
  pgdata: